version: 0.1
environment_variables:
    plaintext:
        S3_BUCKET: "studybuddyshop.com"
        BUILD_ENV: "prod"
phases:
    install:
        commands:
            - pwd
            - ls
            - echo Installing source NPM dependencies...
            - cd \studybuddyangularapp && npm install
            - npm install -g @angular/cli
            - npm i -g awsmobile-cli
    pre_build:
        commands:
          - pwd
          - echo copy private files from s3...
          - aws s3 cp s3://private-config-files/secret ./studybuddyangularapp/src/ --recursive
          - ls \studybuddyangularapp
    build:
        commands:
          - pwd
          - echo $SHELL
          - echo Build started on `date`
          - npm run prod-build --prefix studybuddyangularapp
    post_build:
        commands:
          - ls studybuddyangularapp/dist
          - aws s3 cp studybuddyangularapp/dist s3://studybuddyshop.com --recursive
          - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes