version: 0.1
environment_variables:
    plaintext:
        S3_BUCKET: "studybuddyshop.com"
        BUILD_ENV: "prod"
phases:
    install:
        commands:
            - pwd
            - ls
            #- apt-get -y update
            # Install chrome
            #- apt-get -y install google-chrome-stable
            - echo Installing source NPM dependencies...
            - cd \studybuddyangularapp && npm install
            - npm install -g @angular/cli
            - npm i -g awsmobile-cli
    pre_build:
        commands:
          - pwd
          - echo copy private files from s3...
          - aws s3 cp s3://private-config-files/secret ./studybuddyangularapp/src/ --recursive
          - ls \studybuddyangularapp
    build:
        commands:
          - pwd
          - echo $SHELL
          #- npm run test
          - echo Build started on `date`
          - npm run prod-build --prefix studybuddyangularapp
    post_build:
        commands:
          - ls studybuddyangularapp/dist
          - aws s3 cp studybuddyangularapp/dist s3://studybuddyshop.com --recursive
          - aws cloudfront create-invalidation --distribution-id E1XD6BR65AA6U5 --paths /*
          - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'studybuddyangularapp/dist*'
    discard-paths: yes